[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "torch==2.0.0",
    "transformers",
    "flake8",
    "mypy",
    "numpy",
    "pydantic",
]

[tool.uv.sources]
llm-sdk = {path = "llm_sdk"}
